spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/db_comunidade?serverTimezone=America/Sao_Paulo}
spring.datasource.driverClassName=${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${DATABASE_USERNAME:developer}
spring.datasource.password=${DATABASE_PASSWORD:developer}

spring.jpa.database-platform=${DATABASE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.defer-datasource-initialization=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
